# Generated by Django 4.0.4 on 2022-07-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('year', models.IntegerField()),
                ('owner', models.CharField(max_length=200)),
                ('borrowed', models.BooleanField(default=False)),
                ('lent', models.BooleanField(default=False)),
            ],
        ),
    ]
