# Generated by Django 4.0.4 on 2022-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default='Not Defined', max_length=200),
            preserve_default=False,
        ),
    ]
