# Generated by Django 4.0.4 on 2022-07-05 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_book_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_from',
            field=models.CharField(default='NONE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='borrowing_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 12, 42, 33, 184162)),
        ),
        migrations.AddField(
            model_name='book',
            name='borrowing_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 12, 42, 33, 184162)),
        ),
        migrations.AddField(
            model_name='book',
            name='gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='gift_by',
            field=models.CharField(default='NONE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='gift_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 12, 42, 33, 184162)),
        ),
        migrations.AddField(
            model_name='book',
            name='lending_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 12, 42, 33, 184162)),
        ),
        migrations.AddField(
            model_name='book',
            name='lending_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 12, 42, 33, 184162)),
        ),
        migrations.AddField(
            model_name='book',
            name='lent_by',
            field=models.CharField(default='NONE', max_length=200),
            preserve_default=False,
        ),
    ]
