# Generated by Django 4.0.4 on 2022-07-05 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_book_borrowed_from_book_borrowing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_desc',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 13, 5, 24, 268500)),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 13, 5, 24, 268500)),
        ),
        migrations.AlterField(
            model_name='book',
            name='gift_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 13, 5, 24, 268500)),
        ),
        migrations.AlterField(
            model_name='book',
            name='lending_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 13, 5, 24, 268500)),
        ),
        migrations.AlterField(
            model_name='book',
            name='lending_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 13, 5, 24, 268500)),
        ),
    ]
