# Generated by Django 4.0.4 on 2022-07-05 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_book_short_desc_alter_book_borrowing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowing_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 15, 38, 32, 772365)),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 15, 38, 32, 772365)),
        ),
        migrations.AlterField(
            model_name='book',
            name='gift_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 15, 38, 32, 772365)),
        ),
        migrations.AlterField(
            model_name='book',
            name='lending_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 15, 38, 32, 772365)),
        ),
        migrations.AlterField(
            model_name='book',
            name='lending_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 5, 15, 38, 32, 772365)),
        ),
    ]
